server:
  port: 8761

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: user-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
